Description: Seting up resources to host a static website
Parameters:
  WebsiteDomain:
    Type: String
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - "GET"
            AllowedOrigins:
              - "*"

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: WebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource:
              Fn::Join:
                - ''
                - - Fn::GetAtt: ["WebsiteBucket", "Arn"]
                  - '/*'

  WebsiteHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name:
        Ref: WebsiteDomain

  WebsiteARecord:
    Type: AWS::Route53::RecordSet
    Properties: 
      HostedZoneId: 
        Ref: WebsiteHostedZone
      Name: 
        Ref: WebsiteDomain
      AliasTarget:
        DNSName:
          Fn::GetAtt: [ WebsiteDistribution, DomainName ] 
        HostedZoneId: Z2FDTNDATAQYW2
      Type: A

  WebsiteCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName:
        Ref: WebsiteDomain
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName:
            Ref: WebsiteDomain
          HostedZoneId:
            Ref: WebsiteHostedZone

  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - Ref: WebsiteDomain
        Origins:
          - Id: WebsiteDistribution
            DomainName:
              Fn::GetAtt: [ WebsiteBucket, RegionalDomainName ]
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        PriceClass: PriceClass_100
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          CachePolicyId:
            Ref: WebsiteDistributionCachePolicy
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: WebsiteDistribution
        ViewerCertificate:
          AcmCertificateArn:
            Ref: WebsiteCertificate
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only

  WebsiteDistributionCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        DefaultTTL: 43200
        MaxTTL: 86400
        MinTTL: 3600
        Name: BlogCachePolicy
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingGzip: false
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

